### ISSUE TITLE
Allow passing of kwargs to the requests GET call.

### ISSUE THREAD

**Issue by Mahir-Sparkess** [brazil-data-cube/stac.py#100]
Currently the package doesn't let me use self-certified SSL urls, giving me a no SSLError when instantiating a STAC class.

I can make a PR for my fix to this. I have added **request_kwargs to pass down request parameters down to the GET request in utils._get from the stac class.

**Comment by Mahir-Sparkess** [comment]
Apologies for spamming the issues. I have come across some problems related to my stac endpoint usage and thought these would be some general nice to have solutions.

In terms of uncertified/unsecure URLs I have added **kwargs to the STAC class that will pass the request kwargs down to the get request in the Util. This also covers the get call in the Collection class.

If it's alright I can make a PR, but I shall link my solution [here](https://github.com/cedadev/stac.py/tree/pass-request-kwargs)

**Comment by Mahir-Sparkess** [comment]
Other issues, if I should make new issues away from this do let me know, are:

- My stac endpoint does not have expected providers/summaries as expected in Stac.py, added try case for a valid catch [here](https://github.com/cedadev/stac.py/tree/try-case-summaries-providers):
https://github.com/cedadev/stac.py/blob/1de09a81bd5cb8dd183036195161a6827aee145f/stac/collection.py#L111-L118
- The URL is inconsistent with the rstrip of the '/' on the end of a URL, why not process the '/' on initialisation if URL has a '/' at the end or not. My fork [here](https://github.com/cedadev/stac.py/tree/format-url):
https://github.com/cedadev/stac.py/blob/db978e43ffa570b039ceb2f77831a66d282b570e/stac/stac.py#L38

**Comment by raphaelrpl** [comment]
Hi @Mahir-Sparkess,

Thanks for collaborating with Brazil Data Cube stac.py library.

The changes related across SSL/request kwargs that you have made seems OK for us and it would be great to have these changes integrated in stac.py. Please re-open the PR, so we can validate and integrate in the next version.

> Other issues, if I should make new issues away from this do let me know, are:
> 
> * My stac endpoint does not have expected providers/summaries as expected in Stac.py, added try case for a valid catch [here](https://github.com/cedadev/stac.py/tree/try-case-summaries-providers):
>   https://github.com/cedadev/stac.py/blob/1de09a81bd5cb8dd183036195161a6827aee145f/stac/collection.py#L111-L118
> * The URL is inconsistent with the rstrip of the '/' on the end of a URL, why not process the '/' on initialisation if URL has a '/' at the end or not. My fork [here](https://github.com/cedadev/stac.py/tree/format-url):
>   https://github.com/cedadev/stac.py/blob/db978e43ffa570b039ceb2f77831a66d282b570e/stac/stac.py#L38

For the other changes, please consider to open news issues related.

Based in your points: 
- (1): Sure, we can integrate it. Could you provide an example of summary in your context?
- (2): Its ok. You may also simplify using just `rstrip('/')` instead code checking end of string.

Thanks again for the collaborating :thumbsup:

**Comment by Mahir-Sparkess** [comment]
Thanks for the reply. I shall re-open my PR and make separate issues. My initial PR was an accident on my part trying to open into my fork.
