### ISSUE TITLE
Datetime filter issue

### ISSUE THREAD

**Issue by rolfsimoes** [brazil-data-cube/stac.py#59]
Date filter is not working properly for collection LC8_30_16D_STK-1 (not tested for other collections).

An interval of 14-days is informed but no item is returned.

For the examples bellow, the date parameters of the requests have the same start date but different end dates (highlighted in bold).

--> requested datetime: 2018-08-30/2018-09-12 (interval of 14-days)
http://brazildatacube.dpi.inpe.br/stac/search?collections=LC8_30_16D_STK-1&datetime=2018-08-30/2018-09-12
<-- (no result)

--> requested datetime: 2018-08-30/2018-09-**13** (interval of 15-days)
http://brazildatacube.dpi.inpe.br/stac/search?collections=LC8_30_16D_STK-1&datetime=2018-08-30/2018-09-13
<-- items from 2018-08-29/2018-09-13 interval

--> datetime: 2018-08-30/2018-09-**14** (interval of 16-days)
http://brazildatacube.dpi.inpe.br/stac/search?collections=LC8_30_16D_STK-1&datetime=2018-08-30/2018-09-14
<-- items from 2018-08-29/2018-09-13 (same as of above) and 2018-09-14/2018-09-29 intervals

**Comment by mzaglia** [comment]
[Moved to bdc-stac](https://github.com/brazil-data-cube/bdc-stac/issues/126)
