### ISSUE TITLE
Error on collection.get_items() when there is no "thumbnail" asset

### ISSUE THREAD

**Issue by marujore** [brazil-data-cube/stac.py#95]
`UndefinedError: 'dict object' has no attribute 'thumbnail'` when there is no asset called "thumbnail"

Example:
`import stac`
`service = stac.STAC('https://eod-catalog-svc-prod.astraea.earth', False)`
`collection = service.collection('myd13a1')`
`collection.get_items()`

I believe the error occurs due to the html item template

**Comment by betonr** [comment]
this issue is related to stac_version. In your example, the STAC API is at version 1.0.0-beta.2 and stac.py does not support the version at this time. We need to add models from version 1.0.0 in jsonschemas

**Comment by marujore** [comment]
Can you verify with `https://service-stac.int.bgdi.ch/api/stac/v0.9` (which is 0.9) using the collection `ch.are.agglomerationsverkehr`?
Thank you very much.

**Comment by betonr** [comment]
update your stac.py version to 0.9.0-12, it solves this problem
